# Generated by Django 5.1.5 on 2025-02-04 08:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Comment must be at least 5 characters long'), django.core.validators.RegexValidator(message='Comment contains invalid characters', regex='^[a-zA-Z0-9\\s\\u0600-\\u06FF.,!?()-]+$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be a valid Gmail address', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long'), django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s\\u0600-\\u06FF]+$')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='created_date', verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='وضعیت انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='blog_catego_name_cb8828_idx')],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReplyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long'), django.core.validators.RegexValidator(message='Name can only contain letters and spaces', regex='^[a-zA-Z\\s\\u0600-\\u06FF]+$')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator(message='Email must be a valid Gmail address', regex='^[a-zA-Z0-9._%+-]+@gmail\\.com$')])),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(5, 'Comment must be at least 5 characters long'), django.core.validators.RegexValidator(message='Comment contains invalid characters', regex='^[a-zA-Z0-9\\s\\u0600-\\u06FF.,!?()-]+$')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='کامنت')),
            ],
            options={
                'verbose_name': 'پاسخ کامنت',
                'verbose_name_plural': 'پاسخ کامنت ها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_replyc_created_c52b10_idx')],
            },
        ),
    ]
